// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SRD_SuperToolsEngine","status":true,"description":"The heart of all maker-style plugins; it adds a playtesting editor that can be opened with F12.","parameters":{"Connect Editor":"true","Auto Open Window":"false","Auto Move Window":"true","Menu Editor Exempt List":"[\"Window_BattleLog\",\"Window_MapName\"]"}},
{"name":"SRD_StatDistribution","status":true,"description":"Allows players to distribute points to different stats of the Actors at his or her discretion.","parameters":{"Default Stats":"mhp, mmp, atk, def, mat, mdf, agi, luk","Default Formula":"Math.ceil(level / 10)","Show on Menu":"true","== Stat Reset ==":"","Allow Stat Resets":"true","Reset Gold Cost":"points * 100","== Custom Texts ==":"","Level Up Message":"Got %1 stat points!","Command Name":"Stat Boost","Points Text":"Stat Points:","Upgrade Text":"Upgrade Cost:","Spend Text":"Spend","Reset Text":"Reset","Finish Text":"Finish","== Gauge Options ==":"","Use Gauges":"true","Gauge Height":"14","== Points Label ==":"","Point Icon":"87","Point Text":"Points","Point Color":"#66ff66"}}
];
